### PR TITLE
build(deps)!: upgrade prost to 0.13 for hyper 1.x

### PR DESCRIPTION
**Pull request by tisonkun**
tonic 0.12 depends on prost 0.13

### CODE REVIEW

**Comment by westonpace** [comment]
Hmm...looks like some failures with pbjson.  Want to open an issue at https://github.com/influxdata/pbjson ?  Looks like @tustvold is maintainer so maybe can trade some arrow/df favors :laughing:

**Comment by tisonkun** [comment]
Yeah. This is a deep dependency tree .. I arrive here from upgrading GreptimeDB's tonic version and it depends on datafusion -> substratit and now pbjson ..

**Comment by tisonkun** [comment]
So here it is - https://github.com/influxdata/pbjson/pull/126

The upstream needs to make a release also .. So perhaps take some time.

**Comment by tustvold** [comment]
>  Looks like @tustvold is maintainer so maybe can trade some arrow/df favors

I'm afraid I no longer work at influxdata, but @alamb can probably be persuaded to take a look

**Comment by alamb** [comment]
> So here it is - [influxdata/pbjson#126](https://github.com/influxdata/pbjson/pull/126)
> 
> The upstream needs to make a release also .. So perhaps take some time.

I'll take care of it

**Comment by alamb** [comment]
> So here it is - [influxdata/pbjson#126](https://github.com/influxdata/pbjson/pull/126)
> 
> The upstream needs to make a release also .. So perhaps take some time.

I merged https://github.com/influxdata/pbjson/pull/126 and am tracking the release of the next version via https://github.com/influxdata/pbjson/issues/127

**Comment by alamb** [comment]
Update here is that pbjson 0.7.0 was merged https://github.com/influxdata/pbjson/issues/127 so I think that should unblock some more of the dependency upgrades

**Pull request merged**
