### PR TITLE
[Merged by Bors] - feat: add `version` module with Substrait version information

### PR DESCRIPTION
**Pull request by mbrobbel**
This PR adds a `version` module that relies on some additions to the build
script to provide information about the version of the Substrait submodule that
was used to build the crate. It should be helpful for producers to populate the
version field of a plan. 

Changes:
- Added some tests that check if we are using a tagged Substrait release for the
  builds of this crate (this should help block Dependabot updates to non-tagged
  commits)
- Added a package job to the test workflow to make sure a packaged source builds
  and includes the generated version file
- Added a `semver` features that adds a functions to the `version` module to get
  the version of Substrait as `semver::Version`. The docs (docs.rs and the ones
  deployed to GitHub Pages) now also render this via `doc_auto_cfg`.
- Set the substrait submodule back to v0.21.1. We were 1 commit ahead.

### CODE REVIEW

**Review by westonpace — APPROVED** [review]
I'm somewhat jealous.  I still have to figure this out in Arrow.

**Comment by westonpace** [comment]
Looks like this needs a rebase

**Comment by mbrobbel** [comment]
This changes the substrait version, but it doesn't have to be a breaking change for this project because the additional [commit](https://github.com/substrait-io/substrait/commit/81e34d4054ff0dbde23ac749fbb8fcc232989c5d) only contains additions.

**Pull request closed without merging**
