### PR TITLE
deps: bump substrait proto to v0.18

### PR DESCRIPTION
**Pull request by waynexia**
Signed-off-by: Ruihang Xia <waynestxia@gmail.com>

Closes #15 (maybe the only difference is I'm not bot and am able to sign CLA)🤣

Two things make me bump the version:
- More document in the protobuf will be rendered to docs.rs. The current version doesn't contain so many docs.
- API changes. I want to adapt the new API at the first time so I don't need to make change after my code (the downstream) is initialized.

### CODE REVIEW

**Comment by mbrobbel** [comment]
@jacques-n can you add a dependabot exception to CLAassistant?

**Comment by waynexia** [comment]
So how about let human in 😉 And I'm looking forward to making a new release on this crate (would love to help on the procedure) after we update the proto.

**Comment by mbrobbel** [comment]
An exception for @dependabot was added, so we should be able to move forward with those PRs in the future.

**Comment by waynexia** [comment]
Glad to see it's making progress 😃

**Comment by jacques-n** [comment]
@waynexia , can you rebase? Looks like there is a conflict now.

**Comment by waynexia** [comment]
Thanks for reminding me! This PR is out of date (0.18 < 0.21). I'm going to close it now.

**Pull request closed without merging**
